// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyowetrsgzypudijzvmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5b3dldHJzZ3p5cHVkaWp6dm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzE2MDMsImV4cCI6MjA1ODE0NzYwM30.VcyF5SbQv_dlGo6i6OKTbYSfwHdH-yH83lyVx54dNgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);